services:
  - type: web
    name: django-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn fumolanches_back.wsgi:application --bind 0.0.0.0:$PORT --workers 2
    healthCheckPath:
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: fumolanches_back.settings
      - key: DATABASE_URL
        value: your_database_url
      - key: SECRET_KEY
        value: $SECRET_KEY
